# Generated by Django 6.0 on 2025-12-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learninginsight',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='learninginsight',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
