# Generated by Django 6.0 on 2025-12-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_learninginsight_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learninginsight',
            name='progress',
        ),
        migrations.AddField(
            model_name='learninginsight',
            name='community_uses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learninginsight',
            name='crystal_uses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learninginsight',
            name='library_uses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learninginsight',
            name='mindgarden_uses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learninginsight',
            name='total_actions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learninginsight',
            name='whisper_uses',
            field=models.IntegerField(default=0),
        ),
    ]
